/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:82ac2c1b-3c20-4320-b260-3a0e6dfbf0e2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vrgCTlnT1",
    "aws_user_pools_web_client_id": "2kldievfvkfc91jq9pe1gitet0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3test7vecffjpadkilx2sayssm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
